version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16

    steps:
      - checkout
      - run: echo "MONGO_USER=$MONGO_USER && MONGO_PASS=$MONGO_PASS && MONGO_DOMAIN=$MONGO_DOMAIN && MONGO_DB=$MONGO_DB"
      - run: npm install
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - build
