version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16

    steps:
      - checkout
      - run: echo "MONGO_USER=$MONGO_USER && MONGO_PASS=$MONGO_PASS && MONGO_DOMAIN=$MONGO_DOMAIN && MONGO_DB=$MONGO_DB"
      - run: npm install
      - run: npm test
  deploy:
    machine:
      enabled: true
    steps:
      - run: ssh ec2-user@18.231.4.252 -o StrictHostKeyChecking=no "cd ezops-test-diego-de-melo-gonzaga && sh ./scripts/deploy.sh && exit"
workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
